nombre=input("Ingrese su nombre: ")
edad=input("Edad: ")
ocupacion=input("Ingrese ocupación: ")
lugar=input("En dónde trabajas: ")
caracteristica_1=input("Ingrese 3 características: \n1. > ")
caracteristica_2=input("2. > ")
caracteristica_3=input("3. > ")
pasatiempo=input("Cuál es tu pasatiempo: ")
hacer=input("Qué quieres hacer: ")
print(f"Mi nombre es {nombre}, tengo {edad} años de edad, mi ocupación es de {ocupacion}, y trabajo en {lugar}. Mis principales características es que {caracteristica_1}, {caracteristica_2} y {caracteristica_3}. Las cosas que me gustan hacer son {pasatiempo} y me gustaría poder hacer {hacer}")